//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace FormValidationEdm.Models
{
   
    public partial class tbl_Department
    {
        [Key]
        public int D_Id { get; set; }
        [Required]//We have manually done this,If we update the database this will be removed automatically,so we create a another class called meta class.
        public string D_Name { get; set; }
        public string HOD { get; set; }
    }
}
