//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
namespace EdmValidation.Models
{
   
    public partial class tbl_Department
    {
        public int D_Id { get; set; }


        public string D_Name { get; set; }
        public string HOD { get; set; }
    }
}
